version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gomod-minor-patch:
        update-types: ["minor", "patch"]
      security:
        applies-to: security-updates
        patterns: ["*"]
    labels: ["dependencies", "security"]
